### PR TITLE
fix/issue-939 - Using AIO Event for sending 

### LINKED ISSUE #939: Socket>>sendData: hot-spins if the other side is unresponsive
Get a pair of sockets connected, e.g.:

```smalltalk
accept := Socket newTCP listenOn: 12345 backlogSize: 5.
[ client := Socket newTCP connectTo: NetNameResolver localHostAddress port: 12345 ] fork.
server := accept waitForConnectionFor: 1; accept.
```

Then try to send a message that is too large to fit in any of the various send buffers, and don't do anything on the other end:

```smalltalk
server sendData: (ByteArray new: 10**6 withAll: 37).
```

I expect this to block for, in this case, 60s, then raise an error. Instead, it hot-spins—`sendDone` always returns `true`, so it tries sending, which fails with `EWOULDBLOCK` (as expected), which gets converted to a return value of 0 from `sendSomeData:...`, and around and around we go, with Pharo consuming 100% CPU.

This behavior is definitely new since VM version 10.0.5. Looks to me like it comes from the EPOLL implementation added in May/June 2024, see 1eeb107c. I don't fully understand what's going on—what is the "event system" the comments refer to? Seems like maybe something got half-done and the rest needs to be hooked up?

### PR DESCRIPTION
**Pull request by tesonep**
- Adding a flag to handle if the socket is blocked in a send.
- Handling the async event for this case.

Fix #939

### CODE REVIEW

File: extracted/plugins/SocketPlugin/src/common/SocketPluginImpl.c [hunk 1]
```diff
@@ -261,7 +262,7 @@ typedef struct privateSocketStruct
 #define SOCKETERROR(S)		(PSP(S)->sockError)
 #define SOCKETPEER(S)		(PSP(S)->peer)
 #define SOCKETPEERSIZE(S)	(PSP(S)->peerSize)
-
+#define SOCKET_WATINGTOSEND(S) (PSP(S)->waitingToSend)
```
Comment (mumez) [inline extracted/plugins/SocketPlugin/src/common/SocketPluginImpl.c]: [nitpick] SOCKET_WATINGTOSEND -> SOCKET_WAITINGTOSEND

**Comment by tesonep** [comment]
I have tried, and it looks like it fixes also #1018

**Comment by mumez** [comment]
Just to clarify: The issue on https://github.com/pharo-project/pharo-vm/issues/1018 is only reproduced on the latest Linux VM, but this PR fixes the common part, not the platform-specific part. So, I am unsure how this code resolved the Linux-specific issue.

Could you attach some test code? I'll also test by myself.

**Comment by mumez** [comment]
I hope that the issue at https://github.com/pharo-project/pharo-vm/issues/1018 has been resolved. I'll reopen the issue if the error still occurs on the latest pharo10 branch VM.

**Comment by mumez** [comment]
I think it would be nicer if we have a unit test that shows what has been resolved.
